@startuml SD-Create

participant "Routing" as Routing
participant "Controller" as Controller
participant "Service" as Service
participant "IRepository" as Repository
participant "Mapper" as Mapper
participant "Domain" as Domain
participant "DTO" as DTO
participant "IUnitOfWork" as UnitOfWork

-> Routing : HTTP POST /api/... 
activate Routing

    Routing -> Controller : Create(dto)
    activate Controller

        Controller -> Service : Create(dto)
        activate Service

            Service -> Mapper : ToDomain(dto)
            activate Mapper

                loop for each attribute: 
                    Mapper -> DTO : Get attribute
                    activate DTO

                        DTO --> Mapper : Return attribute
                    deactivate DTO

                    Mapper -> Domain : Set attribute
                    activate Domain

                        Domain --> Mapper : Return attribute
                    deactivate Domain
                end

                Mapper --> Service : domain
            deactivate Mapper

            Service -> Repository : AddAsync(domain)
            activate Repository

                Repository --> Service : ...
            deactivate Repository

            Service -> UnitOfWork : CommitAsync()
            activate UnitOfWork

                UnitOfWork --> Service : ...
            deactivate UnitOfWork

            Service -> Mapper : ToDTO(domain)
            activate Mapper

                loop for each attribute: 
                    Mapper -> Domain : Get attribute
                    activate Domain

                        Domain --> Mapper : Return attribute
                    deactivate Domain

                    Mapper -> DTO : Set attribute
                    activate DTO

                        DTO --> Mapper : Return attribute
                    deactivate DTO
                end

                Mapper --> Service : dto
            deactivate Mapper

            Service --> Controller : dto
        deactivate Service

        Controller --> Routing : Ok(dto)
    deactivate Controller

    <-- Routing : 200 Ok
    
deactivate Routing

@enduml