@startuml uc001-system-sequence-diagram

title System Sequence Diagram (SSD) - UC001
actor Patient as Patient
participant ":System" as System
participant ":IAM" as IAM

activate Patient

    Patient -> System: Register Backoffice User

    activate System

        System --> Patient: Redirect to IAM

    deactivate System

    Patient -> IAM: Register

    activate IAM

        IAM --> Patient: Ask for email

    deactivate IAM

    Patient -> IAM: Input email

    activate IAM

        IAM --> Patient: Ask for password

    deactivate IAM

    Patient -> IAM: Input password

    activate IAM

        IAM -> System: Send user email as token

    deactivate IAM

    activate System

        System -> System: Assign admin/doctor/nurse/technician role to user

        System -> System: Register user in the system

        System -> System: If appliable, link staff's profile to user's account

        System --> Patient: Show success message

    deactivate System

deactivate Patient

@enduml