@startuml SD-Read

actor User as u
participant "file.html" as Html
participant "file.component.ts" as Component
participant "file-model.ts" as Model
participant "file.service.ts" as Service
participant "Backend Module" as Backend

u -> Html: Request for read form
activate Html
    Html -> Component: Read form
    activate Component
        Component -> Model: Read form data
        activate Model
            Model --> Component: Retrieve data
            deactivate Model
        Component -> Service: Send data
        activate Service
            Service --> Backend: http.get(data)
                Backend --> Service: Data Retrieved
            Service -> Service: data.map()
                activate Service
                Service --> Model: Map Data 
                    activate Model
                    Model --> Service: Mapped Data Retrieved
                deactivate Model
            deactivate Service
            Service --> Component: Mapped Data Retrieved
            deactivate Service
        Component --> Html: Form read
        deactivate Component
    Html --> u: Form read
    deactivate Html

@enduml